import { Button, VerticalBox } from "std-widgets.slint";
import "./fonts/Noto_Sans/static/NotoSans-Regular.ttf";

export component AppWindow inherits Window {
    default-font-family: "Noto Sans";
    in-out property<int> counter: 42;
    callback request-increase-value();
    VerticalBox {
        Text {
            text: "Counter: \{root.counter}";
        }
        Button {
            text: "Increase value";
            clicked => {
                root.request-increase-value();
            }
        }
     }
}
